<?php

$beerAsia = [
['nom' => 'BEERLAO',
 'prix' => 1.80,
 'img' => '../asset/img/kevin/Beers/BEER-LAO_resultat_2.jpg',
 'descriptif' => 'Brassée avec un unique riz lao blanchi et eau fraîche naturelle du Laos.',
 'gout' => 3,
 'soif' => 1.5,
 'amertume' => 2,
 'pays' => 'Laos',
 'pourcent' => 5,
 'prixCaisse'  => 9.80, ],

['nom' => 'ASAHI',
 'prix' => 2.60,
 'img' => '../asset/img/kevin/Beers/ASAHI2_resultat_2.jpg',
 'descriptif' => 'La bière blonde la plus vendue au Japon...et dans les restaurants de sushis!',
 'gout' => 5,
 'soif' => 1.5,
 'amertume' => 2,
 'pays' => 'Japon',
 'pourcent' => 5,
 'prixCaisse' => 14.00, ],

['nom' => 'TIGER',
 'prix' => 2.55,
 'img' => '../asset/img/kevin/Beers/TIGER_resultat_2.jpg',
 'descriptif' => 'Une bière blonde premium brassée : malt australien, houblon allemand.',
 'gout' => 2,
 'soif' => 2,
 'amertume' => 1,
 'pays' => 'Singapour',
 'pourcent' => 5.1,
 'prixCaisse' => 15.00, ],

['nom' => 'TSINGTAO',
 'prix' => 2.60,
 'img' => '../asset/img/kevin/Beers/TSINGTAO_resultat_2.jpg',
 'descriptif' => 'La bière chinoise rafraîchissante la plus connue et répandue !',
 'gout' => 2,
 'soif' => 1,
 'amertume' => 1.5,
 'pays' => 'Chine',
 'pourcent' => 5,
 'prixCaisse' => 14.50, ],

['nom' => 'SNOW',
 'prix' => 1.85,
 'img' => '../asset/img/kevin/Beers/SNOW_resultat_2.jpg',
 'descriptif' => 'Une bière lager originaire de Chine avec fermentation basse.',
 'gout' => 3.5,
 'soif' => 2,
 'amertume' => 0.5,
 'pays' => 'Chine',
 'pourcent' => 3.5,
 'prixCaisse' => 10.10, ],

['nom' => 'SINGHA',
 'prix' => 1.55,
 'img' => '../asset/img/kevin/Beers/SINGHA_resultat_2.jpg',
 'descriptif' => 'Une bière premium thailandaise empreinte d’exotisme et d’élégance.',
 'gout' => 3,
 'soif' => 1.5,
 'amertume' => 1.5,
 'pays' => 'Thaïlande',
 'pourcent' => 5,
 'prixCaisse' => 9.00, ],

['nom' => 'CAMBODIA',
 'prix' => 2.00,
 'img' => '../asset/img/kevin/Beers/Cambodia_resultat_2.jpg',
 'descriptif' => 'Elle porte le nom de sa patrie. La bière la plus consommé au Cambodge!',
 'gout' => 2,
 'soif' => 0.5,
 'amertume' => 2,
 'pays' => 'Cambodge',
 'pourcent' => 5,
 'prixCaisse' => 11.00, ],

 ['nom' => 'ANGKOR',
  'prix' => 1.55,
  'img' => '../asset/img/kevin/Beers/ANGKOR-BEER_resultat_2.jpg',
  'descriptif' => 'Une bière blonde type pils brassée au Cambodge. Douce et légère.',
  'gout' => 4,
  'soif' => 2,
  'amertume' => 1.5,
  'pays' => 'Cambodge',
  'pourcent' => 5,
  'prixCaisse' => 8.60, ],

  ['nom' => 'SAIGON',
   'prix' => 2.10,
   'img' => '../asset/img/kevin/Beers/SAIGON_resultat_2.jpg',
   'descriptif' => 'Pils vietnamienne légère et désaltérante brassée avec du malt et du riz.',
   'gout' => 3,
   'soif' => 1.5,
   'amertume' => 1.5,
   'pays' => 'Vietnam',
   'pourcent' => 4.9,
   'prixCaisse' => 11.60, ],
];
