<?php

$biereFrance = array(
    array("titre" => "Kronenbourg",
        "prix"  => 1.80,
        "image"  => "../asset/img/jd/Kronenbourg.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1.5/5",
        "soif" => "1.5/2",
        "amertume" => "2/2",
        "alcool" => "5%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),
    array("titre" => "Desperados",
        "prix"  => 1.80,
        "image"  =>"../asset/img/jd/Desperados.jpeg",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1.5/5",
        "soif" => "1.5/2",
        "amertume" => "2/2",
        "alcool" => "5%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),
    array("titre" => "Or_de_Bauce",
        "prix"  => 1.90,
        "image"  =>"../asset/img/jd/ordebauceg.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "2.5/5",
        "soif" => "0.5/2",
        "amertume" => "1/2",
        "alcool" => "5%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),

    array("titre" => "Apocalypse_Now",
        "prix"  => 2.80,
        "image"  =>"../asset/img/jd/ApocalypseNow.jpeg",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "8%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),

    array("titre" => "Pelforth",
        "prix"  => 2.30,
        "image"  =>"../asset/img/jd/Pelforth.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),   
    
    array("titre" => "Akerbeltz",
        "prix"  => 2.30,
        "image"  =>"../asset/img/jd/Akerbeltz.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),  

    array("titre" => "Cuvée Clarisse",
        "prix"  => 2.90,
        "image"  =>"../asset/img/jd/cuveeClarisse.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),      

    array("titre" => "Jenlain",
        "prix"  => 2.90,
        "image"  =>"../asset/img/jd/jenlain.jpg",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),  


    array("titre" => "Cuvée Clarisse",
        "prix"  => 2.90,
        "image"  =>"../asset/img/jd/cuveeClarisse.png",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
),    


    array("titre" => "Colomba",
        "prix"  => 2.90,
        "image"  =>"../asset/img/jd/colomba.jpg",
        "descriptif" => "Haec habet inposito Bostram varietate Bostram haec gentium Bostram obtemperare rectoreque et atque veterum saepe cautissimas inposito marte castellis et Traianus rectoreque castrisque Traianus inter ingentes urgeret erexit oppida conserta tumore oppida adtributo legibus et ex provinciae imperator habet quoque.",
        "gout" => "1/5",
        "soif" => "1.3/2",
        "amertume" => "2/2",
        "alcool" => "7%",
        "fermentation" => "basse",
        "unite" => 1.80,
        "caisse" => 10.80,
        "fut" => 25
)      
        );